name: Test

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  RS256-tests:
    uses: ./.github/workflows/api-qs-tests.yml
    with:
        sample-directory: '01-Authorization-RS256'
    secrets: inherit
